version: "4"

services:
  latte:
    image: pejmans21/latte:latest
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    expose:
      - 5000
    ports:
      - ${APP_PORT:-5000}:5000
